// Generated by CoffeeScript 1.6.3
var canvasElement, context, drawCurve, getCurve, getSample, height, imageCanvas, init, svg, thickness, width;

imageCanvas = null;

context = null;

canvasElement = null;

width = null;

height = null;

svg = null;

thickness = 40;

getSample = function(context, x, y) {
  return context.getImageData(x, y, 1, 1).data;
};

getCurve = function() {
  var angle, color, i, points, x, y, _i;
  points = [];
  x = Math.floor(Math.random() * width);
  y = Math.floor(Math.random() * height);
  angle = Math.random() * Math.PI * 2;
  for (i = _i = 0; _i <= 30; i = ++_i) {
    angle += Math.random() * Math.PI * 0.02;
    x += Math.sin(angle) * thickness;
    y += Math.cos(angle) * thickness;
    color = getSample(context, x, y);
    points.push([x, y, color[0], color[1], color[2]]);
  }
  return points;
};

drawCurve = function(curve, thickness) {
  var b, c, g, group, l, l1, r, x1, x2, y1, y2, _i, _len, _ref;
  c = curve[0];
  x1 = curve[0][0];
  y1 = curve[0][1];
  group = svg.group();
  _ref = curve.slice(1);
  for (_i = 0, _len = _ref.length; _i < _len; _i++) {
    c = _ref[_i];
    x2 = c[0];
    y2 = c[1];
    r = c[2];
    g = c[3];
    b = c[4];
    l = group.line(x1, y1, x2, y2);
    l.stroke({
      width: thickness,
      color: "rgb(" + r + "," + g + "," + b + ")",
      opacity: 0.4
    });
    l1 = group.line(x1, y1, x2, y2);
    l1.stroke({
      width: thickness / 2,
      color: "rgb(" + r + "," + g + "," + b + ")",
      opacity: 0.8
    });
    x1 = x2;
    y1 = y2;
  }
  return group;
};

init = function(imageUrl) {
  var d, img;
  canvasElement = document.getElementById('canvas');
  imageCanvas = document.getElementById('image');
  width = $(canvasElement).width();
  height = $(canvasElement).height();
  context = imageCanvas.getContext('2d');
  img = new Image();
  img.onload = function() {
    var scale, scaleX, scaleY;
    imageCanvas.width = width;
    imageCanvas.height = height;
    scaleX = width / img.width;
    scaleY = height / img.height;
    scale = Math.max(scaleX, scaleY);
    context.drawImage(img, 0, 0, img.width * scale, img.height * scale);
    return svg = SVG('canvas').size(width, height);
  };
  img.src = imageUrl;
  d = function() {
    var curve, curveData;
    thickness -= 0.1;
    thickness = Math.max(thickness, 10);
    curveData = getCurve();
    return curve = drawCurve(curveData, thickness);
  };
  return setInterval(d, 300);
};

$(document).ready(function() {
  return init('test.jpg');
});
